project:
  type: website
  output-dir: docs

website:
  title: "My Awesome CSCI 0451 Blog"
  output-dir: docs
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





